posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'
urlpatterns = [
    path('store/', views.PostStore.as_view(), name="post_store"),
    path('delete/<int:pk>/', views.delete_post, name="post_delete"),
]

users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('home/', views.UserHome.as_view(), name='user_home'),
    # path('settings/', views.UserSettings.as_views(), name='user_settings'),
    path('users/', views.UsersIndex.as_view(), name="users_index"),
    path('<slug:username>/', views.UserPostsListAndCreate.as_view(), name='user_page'),
    path('<slug:username>/followings/', views.UserFollowings.as_view(), name='user_followings'),
    path('<slug:username>/followers/', views.UserFollowers.as_view(), name='user_followers'),
    path('follow/<slug:username>/', views.followings, name="user_following"),
    path('unfollow/<slug:username>/', views.unfollowings, name="user_unfollowing"),
]

whisper/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include
from django.views.generic.base import TemplateView
from . import settings


urlpatterns = [
    path('', TemplateView.as_view(template_name = "index.html"), name="index"),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('users.urls')),
    path('posts/', include('posts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/common-parts/message.html
<div class="row">
    <div class="my-div-style w-100">
        <ul class="messages" style="list-style:none; padding:0 1rem;">
            {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    {{ message }}
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

templates/common-parts/navigation.html
<header class="mb-4">

    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">

        <a href=
            {% if user.is_authenticated %}
                "{% url 'users:user_home' %}"
            {% else %}
                "/"
            {% endif %}
            class="navbar-brand">
            {{ SITE_NAME }}
        </a>

        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#nav-bar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="nav-bar">
            <ul class="navbar-nav mr-auto"></ul>
            <ul class="navbar-nav">

                {% if user.is_authenticated %}
                    <li class="nav-item"><a href="{% url 'users:users_index' %}" class="nav-link">Users</a></li>
                    <li class="nav-item dropdown">
                        <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle">
                            {{ user.username }}
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <ul class="dropdown-item">
                                <li class="dropdown-item"><a href="{% url 'users:user_home'%}">TimeLine</a></li>
                                <li class="dropdown-item"><a href="{% url 'users:user_page' user.username %}">Posts</a></li>
                                <li class="dropdown-item"><a href="{% url 'users:user_followings' user.username %}"> Followings</a></li>
                                <li class="dropdown-item"><a href="{% url 'users:user_followers' user.username %}">Followers</a></li>
                                <li class="dropdown-divider"></li>
                                <li class="dropdown-item">
                                    <a href="{% url 'account_logout' %}">Log Out</a>
                                </li>
                            </ul>
                        </ul>
                    </li>

                {% else %}
                    <li class="nav-item {% block active_signup %}{% endblock active_signup %}">
                        <a href="{% url 'account_signup' %}" class="nav-link">Sign Up</a>
                    </li>
                    <li class="nav-item {% block active_login %}{% endblock active_login %}">
                        <a href="{% url 'account_login' %}" class="nav-link">Log In</a>
                    </li>

                {% endif %}
            </ul>
        </div>
    </nav>
</header>

templates/common-parts/navtabs.html
<ul class="nav nav-tabs nav-justified mb-3">
    <li class="nav-item"><a href="{% url 'users:user_page' cuser.username %}" class="nav-link">My Posts</a></li>
    <li class="nav-item"><a href="{% url 'users:user_followings' cuser.username %}" class="nav-link">Followings <span class="badge badge-secondary">{{ cuser.followings.all.count }}</span></a></li>
    <li class="nav-item"><a href="{% url 'users:user_followers' cuser.username %}" class="nav-link">Followers <span class="badge badge-secondary">{{ cuser.followers.all.count }}</span></a></li>
</ul>

templates/common-parts/user-card.html
{% load static %}
<div class="card">
    <div class="card-header">
        <h3 class="card-title">{{ cuser.username }}</h3>
    </div>
    <div class="card-body">
        <img src="{% static 'img/noimage.png' %}" size="500" alt="" class="rounded img-fluid">
    </div>
</div>
{% if user.id == cuser.id %}
    <form method="post" name="post_form" id="post_form">
        {% csrf_token %}
        <div class="from-group">
            {{ form.content }}
        </div>
        <button class="btn btn-primary" name="post_form" type='submit'>投稿</button>
    </form>
{% else %}
    {% include 'parts/follow_button.html' with user=user cuser=cuser only %}

{% endif %}