posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'
urlpatterns = [
    path('store/', views.PostStore.as_view(), name="post_store"),
    path('delete/<int:pk>/', views.delete_post, name="post_delete"),
]

users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('home/', views.UserHome.as_view(), name='user_home'),
    # path('settings/', views.UserSettings.as_views(), name='user_settings'),
    path('users/', views.UsersIndex.as_view(), name="users_index"),
    path('<slug:username>/', views.UserPostsListAndCreate.as_view(), name='user_page'),
    path('<slug:username>/followings/', views.UserFollowings.as_view(), name='user_followings'),
    path('<slug:username>/followers/', views.UserFollowers.as_view(), name='user_followers'),
    path('follow/<slug:username>/', views.followings, name="user_following"),
    path('unfollow/<slug:username>/', views.unfollowings, name="user_unfollowing"),
]

whisper/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include
from django.views.generic.base import TemplateView
from . import settings


urlpatterns = [
    path('', TemplateView.as_view(template_name = "index.html"), name="index"),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('users.urls')),
    path('posts/', include('posts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from accounts.models import CustomUser


class Post(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT, related_name='post')
    content = models.TextField(verbose_name='本文', blank=False, null=False)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural ='Post'

    def __str__(self):
        return self.content

users/models.py
from django.db import models


# Create your models here.
class UsersRelation(models.Model):
    
    # import CustomUserで参照しようとするとエラーが出るため、第一引数はpathを使用すること
    follower = models.ForeignKey("accounts.CustomUser", on_delete=models.CASCADE, related_name='followers_relation')

    following = models.ForeignKey("accounts.CustomUser", on_delete=models.CASCADE, related_name='followings_relation')

    class Meta:
        unique_together = ('follower', 'following')

posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('content',)

        widgets = {
            'content': forms.Textarea(attrs={'rows':3,}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

posts/views.py
from django.shortcuts import get_object_or_404
from django.views import generic
from .models import Post
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import PostForm
from django.http import HttpResponseRedirect

# 未使用
# class PostsIndex(LoginRequiredMixin, generic.ListView):
#     context_object_name = 'posts'
#     login_url = 'account_login'
#     model = Post
#     template_name = 'posts_index.html'
#     # paginate_by = 20

#     def get_queryset(self):
#         posts = Post.objects.filter(user=self.request.user).order_by('-created_at')
#         return posts


class PostStore(LoginRequiredMixin, generic.CreateView):
    model = Post
    template_name = 'post_store.html'
    form_class = PostForm
    # success_url = reverse_lazy('posts:posts_index')

    def form_valid(self, form):
        post = form.save(commit=False)
        post.user = self.request.user
        post.save()
        messages.success(self.request, 'ポストを作成しました。')
        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))
        # return super().form_valid(form) #リダイレクトさせない場合

    def form_invalid(self, form):
        messages.error(self.request, "ポストの作成に失敗しました。")
        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))
        # return super().form_invalid(form)


def delete_post(request, pk):

    post = get_object_or_404(Post, id=pk)
    user_id = request.user.id

    if post.user_id == user_id:
        post.delete()
        messages.success(request, 'ポストを削除しました。')

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

users/views.py
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls.base import reverse_lazy
from django.views import generic
from django.contrib import messages
from django.http import HttpResponseRedirect

from accounts.models import CustomUser
from posts.views import PostStore
from users.models import UsersRelation

from django.core.exceptions import ObjectDoesNotExist


class UsersIndex(LoginRequiredMixin, generic.ListView):
    context_object_name = 'cusers'
    model = CustomUser
    template_name = 'users_index.html'
    paginate_by = 10
    
    def get_queryset(self):
        cusers = CustomUser.objects.all()
        return cusers


class UserShow(LoginRequiredMixin, generic.DetailView,):
    context_object_name = 'cuser'
    model = CustomUser
    slug_field = "username"
    slug_url_kwarg = "username"
    template_name = 'user_page.html'

    def get_queryset(self):
        cuser = CustomUser.objects.filter(username=self.kwargs.get("username"))
        return cuser


class UserHome(PostStore):
    def get(self,request, *args, **kwargs):
        form_view = PostStore.get(self, request, *args, **kwargs)
        form_data = form_view.context_data['form']
        context = {'form':form_data}

        return render(request, 'home.html', context)


class UserPostsListAndCreate(UserShow, PostStore,):
    def get(self, request, *args, **kwargs):
        form_view = PostStore.get(self, request, *args, **kwargs)
        form_view.success_url = reverse_lazy('posts:users_index')
        form_data = form_view.context_data['form']
        list_view = UserShow.get(self, request, *args, **kwargs)
        list_data = list_view.context_data['cuser']
        context = {'form':form_data, 'cuser':list_data}

        return render(request, 'user_page.html', context)


class UserFollowings(UserShow, PostStore):
    def get(self, request, *args, **kwargs):
        form_view = PostStore.get(self, request, *args, **kwargs)
        form_data = form_view.context_data['form']
        list_view = UserShow.get(self, request, *args, **kwargs)
        list_data = list_view.context_data['cuser']
        
        context = {'form':form_data, 'cuser':list_data}

        return render(request, 'followings.html', context)


class UserFollowers(UserShow, PostStore):
    def get(self, request, *args, **kwargs):
        form_view = PostStore.get(self, request, *args, **kwargs)
        form_data = form_view.context_data['form']
        list_view = UserShow.get(self, request, *args, **kwargs)
        list_data = list_view.context_data['cuser']

        context = {'form':form_data, 'cuser':list_data}

        return render(request, 'followers.html', context)


# フォローする
def followings(request, username):

    user = request.user

    try:
        follow_user = get_object_or_404(CustomUser, username=username)

        UsersRelation.objects.create(following=follow_user, follower=user)

        messages.success(request, follow_user.username + 'をフォローしました。')

    except ObjectDoesNotExist:
        
        messages.error(request, '該当のユーザーは存在しません。')

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


# フォロー解除
def unfollowings(request, username):

    user = request.user

    try:
        follow_user = get_object_or_404(CustomUser, username=username)

        UsersRelation.objects.filter(following=follow_user, follower=user).delete()

        messages.success(request, follow_user.username + 'をフォロー解除しました。')

    except ObjectDoesNotExist:
        messages.error(request, '該当のユーザーは存在しません。')

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

templates/parts/follow_button.html
{% load user_filters %}

{% if user.id != cuser.id %}

    {% with bool=user.followings.all|get_following:cuser.pk %}
        {% if bool %}
            <a href="{% url 'users:user_unfollowing' cuser.username %}" class="btn btn-danger btn-block">
                フォロー解除
            </a>
        {% else %}
            <a href="{% url 'users:user_following' cuser.username %}" class="btn btn-primary btn-block">
                フォローする
            </a>
        {% endif %}
    {% endwith %}

{% endif %}

templates/parts/posts.html
{% load static %}
{% load order_by %}

<ul class="list-unstyled">
    {% for post in posts|order_by:'-created_at' %}
        <li class="media mb-3">
            <img src="{% static 'img/noimage.png' %}" alt="" class="mr-2 rounded" size="75px" height="60px">
            <div class="media-body">
                <div>
                    <a href="{% url 'users:user_page' post.user.username %}">{{ post.user.username }}</a>
                </div>
                <div>
                    <p class="mb-0">{{ post.content }}</p>
                    <span class="text-muted">posted at {{ post.created_at }}</span>
                </div>
                <div>
                    {% if user.pk == post.user.pk %}
                        <a href="{% url 'posts:post_delete' post.pk %}" class="btn btn-danger btn-sm">
                            削除
                        </a>
                    {% endif %}
                </div>
            </div>
        </li>
    {% endfor %}
</ul>

templates/parts/users.html
{% load static %}

{% if cusers %}
    <ul class="list-unstyled">
        {% for cuser in cusers %}
            <li class="media">
                <img src="{% static 'img/noimage.png' %}" alt="" class="mr-2 rounded" size="75px" height="60px">
                <div class="media-body">
                    <div>
                        {{cuser.username}}
                    </div>
                    <div>
                        <p>
                            <a href="{% url 'users:user_page' cuser.username %}">
                                View Profile
                            </a>
                        </p>
                    </div>
                    <div>
                        {% include 'parts/follow_button.html' with cuser=cuser user=user only %}
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>該当ユーザーはいません</p>
{% endif %}